name: eda_penguins
channels:
  - conda-forge
  - defaults
dependencies:
  - empiricaldist
  - fs
  - jupyter
  - jupyterlab
  - matplotlib
  - pandas
  - pathlib
  - pip
  - pyjanitor
  - pyprojroot
  - python=3.7
  - seaborn
  - setuptools